-- ============================================================================
-- COACHING AGENT DATABASE EXTENSIONS
-- Tables for: Training Plans, Assigned Drills, Mental Assessment, Peer Benchmarks
-- ============================================================================

-- 1. TRAINING PLANS TABLE
-- Stores personalized training schedules generated by coach agent
CREATE TABLE IF NOT EXISTS public.training_plans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Plan details
  focus_weakness TEXT NOT NULL, -- e.g., 'net_play', 'defense', 'stamina'
  duration_weeks INTEGER NOT NULL DEFAULT 2, -- 1-4 weeks
  days_per_week INTEGER NOT NULL DEFAULT 3, -- Training frequency
  
  -- Structured plan data
  weekly_schedule JSONB NOT NULL, -- Array of weeks with daily drills
  expected_outcome TEXT,
  progression_level TEXT, -- 'beginner', 'intermediate', 'advanced', 'elite'
  
  -- Status tracking
  status TEXT DEFAULT 'active', -- 'active', 'completed', 'paused', 'abandoned'
  progress_percentage NUMERIC DEFAULT 0,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. ASSIGNED DRILLS TABLE
-- Tracks specific drills assigned to member (from training plans)
CREATE TABLE IF NOT EXISTS public.assigned_drills (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  training_plan_id UUID NOT NULL REFERENCES public.training_plans(id) ON DELETE CASCADE,
  
  -- Drill details
  drill_name TEXT NOT NULL,
  drill_type TEXT, -- 'technique', 'conditioning', 'tactical', 'match_simulation'
  description TEXT,
  
  -- Reps and schedule
  sets INTEGER NOT NULL DEFAULT 3,
  reps_per_set INTEGER NOT NULL DEFAULT 15,
  rest_seconds INTEGER DEFAULT 60,
  duration_minutes INTEGER DEFAULT 30,
  
  -- Difficulty progression
  current_difficulty TEXT DEFAULT 'beginner', -- 'beginner', 'intermediate', 'advanced'
  next_difficulty TEXT,
  
  -- Completion tracking
  assigned_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  target_completion_date TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  
  -- Performance
  completion_count INTEGER DEFAULT 0,
  quality_score NUMERIC, -- 1-10 rating from member
  notes TEXT,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. MENTAL ASSESSMENT TABLE
-- Tracks psychological factors: confidence, pressure response, mentality, etc.
CREATE TABLE IF NOT EXISTS public.mental_assessment (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Assessment types
  assessment_type TEXT NOT NULL, -- 'confidence', 'pressure_response', 'consistency', 'winning_mentality'
  
  -- Scores (1-100)
  confidence_level NUMERIC,
  pressure_response_score NUMERIC,
  consistency_score NUMERIC,
  winning_mentality_score NUMERIC,
  overall_psychological_score NUMERIC,
  
  -- Assessment results
  findings JSONB, -- { assessment, recommendation, score, description }
  mental_strengths TEXT[], -- Array of strengths
  improvement_areas TEXT[], -- Array of areas to work on
  recommendations TEXT[], -- Array of specific recommendations
  
  -- Context
  recent_matches_analyzed INTEGER,
  performance_notes TEXT,
  
  -- Metadata
  assessed_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. PEER BENCHMARKS TABLE
-- Cached peer comparison data for quick lookups
CREATE TABLE IF NOT EXISTS public.peer_benchmarks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Benchmark level
  skill_level TEXT NOT NULL, -- 'beginner', 'intermediate', 'advanced', 'competitive'
  
  -- Benchmark metrics
  avg_win_rate NUMERIC,
  avg_score NUMERIC,
  avg_consistency NUMERIC,
  avg_match_count INTEGER,
  
  -- User vs benchmark
  user_win_rate NUMERIC,
  user_score NUMERIC,
  user_consistency NUMERIC,
  
  -- Gaps and advantages
  competitive_gaps JSONB, -- Array of metric gaps
  user_advantages TEXT[], -- Areas where user excels
  improvement_priorities TEXT[], -- Ranked list of what to improve
  
  -- Performance comparison
  percentile_rank NUMERIC, -- Where user ranks in skill level (0-100)
  
  -- Metadata
  calculated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. COACHING AGENT LOGS TABLE
-- Tracks all agent decisions, tool calls, and autonomy actions
CREATE TABLE IF NOT EXISTS public.coaching_agent_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Agent action
  agent_action TEXT NOT NULL, -- 'analyze', 'generate_plan', 'predict', 'recommend'
  action_trigger TEXT, -- What caused this action (user query, auto-check, etc)
  
  -- Tools executed
  tools_executed TEXT[], -- e.g., ['analyze_tactical_patterns', 'generate_training_plan']
  tool_results JSONB, -- Full results from each tool
  
  -- Agent reasoning
  reasoning TEXT,
  decisions_made TEXT[],
  
  -- Autonomy level
  autonomy_mode TEXT DEFAULT 'responsive', -- 'responsive' or 'autonomous'
  required_user_confirmation BOOLEAN DEFAULT false,
  
  -- Outcome
  action_items_generated INTEGER,
  database_updates TEXT[], -- What was saved to DB
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_training_plans_user ON public.training_plans(user_id, status);
CREATE INDEX IF NOT EXISTS idx_training_plans_status ON public.training_plans(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_assigned_drills_user ON public.assigned_drills(user_id, completed_at);
CREATE INDEX IF NOT EXISTS idx_drills_plan ON public.assigned_drills(training_plan_id);
CREATE INDEX IF NOT EXISTS idx_mental_assessment_user ON public.mental_assessment(user_id, assessed_date DESC);
CREATE INDEX IF NOT EXISTS idx_peer_benchmarks_user_level ON public.peer_benchmarks(user_id, skill_level);
CREATE INDEX IF NOT EXISTS idx_coaching_logs_user ON public.coaching_agent_logs(user_id, created_at DESC);

-- ============================================================================
-- ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================================================

ALTER TABLE public.training_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assigned_drills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mental_assessment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.peer_benchmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coaching_agent_logs ENABLE ROW LEVEL SECURITY;

-- Users can only access their own data
CREATE POLICY "Users can view own training plans" ON public.training_plans
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users can manage own training plans" ON public.training_plans
  FOR ALL USING (user_id = auth.uid());

CREATE POLICY "Users can view own assigned drills" ON public.assigned_drills
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users can manage own assigned drills" ON public.assigned_drills
  FOR ALL USING (user_id = auth.uid());

CREATE POLICY "Users can view own mental assessments" ON public.mental_assessment
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users can insert own mental assessments" ON public.mental_assessment
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can view own peer benchmarks" ON public.peer_benchmarks
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users can insert own peer benchmarks" ON public.peer_benchmarks
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can view own coaching logs" ON public.coaching_agent_logs
  FOR SELECT USING (user_id = auth.uid());

-- Service role can manage all (for API operations)
CREATE POLICY "Service role manages all training plans" ON public.training_plans
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role manages all drills" ON public.assigned_drills
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role manages all assessments" ON public.mental_assessment
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role manages all benchmarks" ON public.peer_benchmarks
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role manages all logs" ON public.coaching_agent_logs
  FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- GRANTS
-- ============================================================================

GRANT SELECT, INSERT, UPDATE ON public.training_plans TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.assigned_drills TO authenticated;
GRANT SELECT, INSERT ON public.mental_assessment TO authenticated;
GRANT SELECT, INSERT ON public.peer_benchmarks TO authenticated;
GRANT SELECT ON public.coaching_agent_logs TO authenticated;

GRANT ALL ON public.training_plans TO service_role;
GRANT ALL ON public.assigned_drills TO service_role;
GRANT ALL ON public.mental_assessment TO service_role;
GRANT ALL ON public.peer_benchmarks TO service_role;
GRANT ALL ON public.coaching_agent_logs TO service_role;

-- ============================================================================
-- TRIGGERS FOR AUTO-UPDATES
-- ============================================================================

-- Auto-update training_plan progress
CREATE OR REPLACE FUNCTION update_training_plan_progress()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.training_plans
  SET 
    progress_percentage = (
      SELECT COUNT(*) FILTER (WHERE completed_at IS NOT NULL) * 100.0 / COUNT(*)
      FROM public.assigned_drills
      WHERE training_plan_id = NEW.training_plan_id
    ),
    updated_at = NOW()
  WHERE id = NEW.training_plan_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_training_plan_progress
  AFTER UPDATE ON public.assigned_drills
  FOR EACH ROW
  EXECUTE FUNCTION update_training_plan_progress();

-- Auto-update plan status to completed
CREATE OR REPLACE FUNCTION check_plan_completion()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.training_plans
  SET 
    status = CASE
      WHEN progress_percentage >= 100 THEN 'completed'
      WHEN progress_percentage > 0 THEN 'active'
      ELSE 'active'
    END,
    completed_at = CASE
      WHEN progress_percentage >= 100 THEN NOW()
      ELSE NULL
    END,
    updated_at = NOW()
  WHERE id = NEW.training_plan_id
  AND progress_percentage >= 100;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_check_plan_completion
  AFTER UPDATE ON public.training_plans
  FOR EACH ROW
  EXECUTE FUNCTION check_plan_completion();

-- Comments
COMMENT ON TABLE public.training_plans IS 'Personalized training schedules generated by Coach Agent';
COMMENT ON TABLE public.assigned_drills IS 'Specific drills from training plans assigned to member';
COMMENT ON TABLE public.mental_assessment IS 'Psychological assessment: confidence, pressure, mentality, consistency';
COMMENT ON TABLE public.peer_benchmarks IS 'Cached peer comparison for quick benchmarking lookups';
COMMENT ON TABLE public.coaching_agent_logs IS 'Audit trail of coach agent decisions and tool executions';
